name: Build and Release Touhou Cursors

on:
  push:
    branches: [main]
    paths:
      - "cursor_data.json"
      - "CursorConverter/**"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up Python
        uses: actions/setup-python@v5.6
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process Touhou Cursors
        run: |
          mkdir -p dist
          python process_cursors.py

      - name: Verify Generated Files
        run: |
          if [ -z "$(ls -A dist/*.zip)" ]; then
            echo "No zip files found in dist directory!"
            exit 1
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ANIME_RELEASE_TOKEN }}
        with:
          tag_name: touhou-cursors-v${{ github.run_number }}
          name: Touhou Cursors Release v${{ github.run_number }}
          body: |
            Release of Touhou cursor sets (1-20)

            This release includes processed cursor sets for all characters from:
            - 東方マウスカーソル　1～10 (Touhou Mouse Cursors 1-10)
            - 東方マウスカーソル　11～20 (Touhou Mouse Cursors 11-20)

            **Changelog:**
            - Updated cursor processing logic
            - Improved compatibility with Linux systems
          files: |
            dist/*.zip
          draft: false
          prerelease: false
